default:
  workbook_properties:
    creator: "Analysis Function"
    title: "example workbook"
    subject: "example subject"
    category: "example"
    modifier: "Analysis Function"
    keywords:
      keyword1: "example"
      keyword2: "demonstration"
      keyword3: "config.yaml"
    comments: "example"
    manager: "Analysis Function manager"
    company: "Analysis Function"
  workbook_format:
    base_font_name: "Arial"
    base_font_size: 12
    table_header_size: 14
    sheet_header_size: 16
    cellwidth_default: 16
    cellwidth_wider: 32
    nchar_break: 50
    decimal_places:
      Contents:
        default: 0
      Notes:
        default: 0
      Table_1:
        default: 0
        column2: 2
        column3: 2
        column4: 4
      Table_2:
        default: 0
minimum:
  workbook_properties:
    creator: "Analysis Function"
    title: "example workbook"
    keywords:
      keyword1: "example"
      keyword2: "demonstration"
      keyword3: "config.yaml"
